### ISSUE TITLE
Docker command doesn't work

### ISSUE THREAD

**Issue by jtrbalic** [jkleczkowski/teamcity-agent-dotnet-core#1]
Hi,

I am trying to use this agent to build my asp.net-core 2.0 app.
It is working fine for the building but I want to add a build step to create docker image, to execute command like:

docker build -t my-image .

But it's failing with error:

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Is there any way to get this agent to create docker images after build

**Comment by jkleczkowski** [comment]
Hi @carpics 
You have to provide DOCKER_HOST enviroment variable while creating container and of course your docker machine must listen at this endpoint

docker run --name tca1 -d \
    --restart=unless-stopped \
    -e SERVER_URL="http://x.x.x.x:yyyy" \
    -e AGENT_NAME="my_tc_agent" \
    **-e DOCKER_HOST="tcp://YOURS_DOCKER_MACHINE_IP_:YOURS_DOCKER_MACHINE_PORT"** \
    jkleczkowski/teamcity-agent-dotnet-core

or You can try with binding you docker socket with container:
   **-v /var/run/docker.sock:/var/run/docker.sock:ro**

**Comment by jtrbalic** [comment]
Thanks @jkleczkowski, this is working fine.
